### PR TITLE
Whitespace, commas, semicolons.

### PR DESCRIPTION
**Pull request by mlrawlings**
As discussed in https://github.com/marko-js/marko/issues/424, https://github.com/marko-js/marko/issues/403, and https://github.com/philidem/htmljs-parser/issues/41.

### Whitespace around equal signs
```js
var foo = 123
```
```html
<img src = "foo.png"/>
```

### Semicolons to (optionally) end concise tags
```js
var foo = 123;
```
Semicolons can also be used to begin a content block on the same line, similar to `-`:
```js
div; Hello world
```

### Commas to (optionally) separate values
```js
var foo = 123, bar = 456
```
```html
<img id = "abc", src = "xyz.png"/>
```
Commas can also be used to allow a concise tag's attributes to continue on the next line:
```js
var foo = 123,
    bar = 456
```
If one attribute is followed by a comma, all attributes are required to be comma delimited:
```js
// PARSE ERROR - MISSING COMMA AFTER ATTRIBUTE FOO:
var foo = 123 bar = 456, baz = 789 
```

### Complex attribute values with unenclosed whitespace:
```js
var foo = 1 + 2
```
```html
<div class = isHidden && 'hidden'></div>
```
If there is more than one attribute for a tag with an attribute that has unenclosed whitespace, attributes must be comma delimited:
```js
var foo = 1 + 2, bar = 4 + 5
```
```html
<img class = isHidden && 'hidden', src = "foo.png"/>
```

### CODE REVIEW

**Comment by mlrawlings** [comment]
**NOTE**: This currently breaks the `<import>` tag for the case where it looks like:
```js
import $, { fn } from 'jquery'
```

Scott already created a method to get all a tag's attributes as a single string, we probably need to add a way for a tag to let the parser know that's what it's going to do so it can skip any attribute restrictions and just look for the end of the tag.

**Comment by Hesulan** [comment]
@mlrawlings Could the semicolon keep the parser in tag mode? For example:
```
ul; li for(item in data.items) - ${item}
```
instead of
```
ul
    li for(item in data.items) - ${item}
```

**Comment by mlrawlings** [comment]
I like that thought.  It should be a very simple change.

**Comment by Hesulan** [comment]
Awesome! That would make concise mode even more concise. :)  I love all the rest of these changes too.

As for breaking `<import>`, would it be possible for the comma to only apply when parsing attribute assignments (anything after a `=`) and only when at the top level (not within brackets or parenthesis, aka an object or expression assignment)? I'm not sure how easy that would be, just throwing it out there.

**Comment by mindeavor** [comment]
I had liked the comma separated version, but on further thought I think it doesn't make sense given what's already in place.

Once you allow spaces around `=`, this is already possible:

    
    var foo = 11 bar = 22

and by extension, allowing a expression would let you do:

    
    var foo = 11 + x bar = 22

which I think is ok now. The plain text may look strange, but proper syntax highlighting would make it easy to read. Technically the grammar is unambiguous, so there should be no problems there.

What you see above is the "worst case"; a developer can choose to make this more readable with relative ease. Examples:

```html
    <!-- extra space -->
    <img id = myVar + 1  src = myOtherVar />
    var foo = 11 + x  bar = 22

    <!-- parens -->
    <img id = (myVar + 1) src = myOtherVar />
    var foo = (11 + x) bar = 22

    <!-- Zero spaces, parens -->
    <img id=(myVar + 1) src=myOtherVar />
    var foo=(11 + x) bar=22
```

Personally I think zero spaces around `=` and required parenthesis is the most elegant solution. But if commas were introduced, I wouldn't want to see commas required in some cases, but optional in others – at least, not in the HTML syntax please :)

**Comment by patrick-steele-idem** [comment]
@mlrawlings Are you thinking commas should be required for the following (simple attribute values with space around the `=` sign)?:

```xml
<a href = "http://markojs.com" class = "foo">Marko</a>
```

**Comment by mlrawlings** [comment]
No, I wanted to make sure valid HTML works as is.  But having a space in an attribute value is not valid html. That's where commas are required (currently). 

To be clear, this is not necessary to parse and it took extra effort to enforce and removing this restriction would mean just deleting some code.

**Comment by mlrawlings** [comment]
@mindeavor To be clear, the following are both valid and don't require commas because there's not any unenclosed whitespace in the attribute value:
```html
<!-- parens -->
<img id = (myVar + 1) src = myOtherVar />
var foo = (11 + x) bar = 22

<!-- Zero spaces, parens -->
<img id=(myVar + 1) src=myOtherVar />
var foo=(11 + x) bar=22
```

**Comment by Hesulan** [comment]
@mlrawlings I completely agree with having commas between every attribute when using whitespace, but I think it really comes down to a style preference. I'm not sure it's the parser's place to enforce that when there's nothing to gain from it, computationally speaking.

As for the HTML spec, I'm not sure I understand. Is there a case where these changes would break valid HTML attributes if commas weren't required?

**Comment by mlrawlings** [comment]
No, Patrick was asking if commas were required for just the spaces around
the equal sign, which if they were would break the html spec.

**Comment by scttdavs** [comment]
I like the idea of this, and what it would do to concise syntax (like the example from the other linked issue above):
```javascript
import { calc } from './helpers'

var sum = data.value + 5
var calculated = calc(data.value, 2)

<div>${calculated}</div>
```

But I don't really like what it does to the html syntax. I suppose it's ok since it is still optional and you could write html syntax code like you would before. 

Do you think we are "tricking" the user into thinking they can write any valid js in there when it's really marko designed to look like js? I'd almost want to start using arrow tags and whatnot given the code above, but if there was some enforcement to a different specification, that line between real js and marko would always be known.

Anywho, with the import tag, we could also just change the 'import parser' to use all attributes, where ones before the attribute equaling `from` are assignments, and afterward is the source. Or like Michael said, allow the tag to opt out of this kind of parsing altogether. 

Also curious:
> a method to get all a tag's attributes as a single string

What does that method return now (with this new version of htmljs-parser)? Because it's using htmljs-parser's start and end points for the tag to generate it.

**Comment by patrick-steele-idem** [comment]
We had a meeting to discuss this. Here are the raw notes: https://gist.github.com/patrick-steele-idem/5917692db3a2ab46ccc29c9d87518b72

**Comment by mindeavor** [comment]
I found this interesting:

```
// ERROR!:
div foo=1 bar=2,
    baz=3
```

Does this mean commas are all-or-nothing?

**Comment by mlrawlings** [comment]
> Do you think we are "tricking" the user into thinking they can write any valid js in there when it's really marko designed to look like js? I'd almost want to start using arrow tags and whatnot given the code above, but if there was some enforcement to a different specification, that line between real js and marko would always be known.

@scttdavs I think this is a valid concern, it's nice to be familiar, but at some point it does break down. I think it's important that we always talk about these as tags and perhaps show the `<var foo=123/>` as well as the `var foo = 123;` syntax.

> We had a meeting to discuss this. Here are the raw notes.

To summarize a few things from this meeting:

### Nothing allowed after a semicolon
 We're not going to allow anything (except comments) after `;` for now... though I do like the idea of entering back into tag mode.  By taking a strict stance now, we can relax it later without it being a breaking change.  I'll convince you all later :smirk:

For the record, the main argument (that I remember) was that we don't want to encourage the one-liners because we may end up in a coffeescript situation where developers try to do everything on one line:
```coffeescript
(n) -> (p.push i for i in [2..n] when not (j for j in (p or p=[]) when i%j == 0)[0]) and n in p
```

That and it's another thing to document.

### Commas
We're taking a similar approach with the commas - at least for now, we can always relax the rules, but it would be difficult to try to enforce them after the fact.

### Concise mode text
`-` to start an html block will be deprecated in v3. Two (or more) dashes will be required.  This is partly to allow `var foo = 3 - 2;` without any ambiguity and keep consistency throughout the language.   

#### Two (or more) dashes followed by a space and some text indicate one line of an html text block:
```
div class="foo" -- Hello World
```
```
div class="foo" 
    -- Hello World
```

#### Two (or more) dashes followed by a line break indicate the beginning of a multiline html text block.  The lines that follow must maintain the indentation or they will enter back into concise mode as a sibling tag:
```
div class="foo" -- 
    Hello World
    What's up?
span -- Meh
```
```
div class="foo" 
    -- 
    Hello World
    What's up?
span -- Meh
```

#### A multiline html text block can be ended by the same number of dashes that opened it so that additional children can be added to the parent tag:
```
div class="foo" -- 
    Hello World
    What's up?
    --
    span -- Meh.
```
```
div class="foo" 
    -- 
    Hello World
    What's up?
    --
    span -- Meh.
```

**Comment by Hesulan** [comment]
Regarding the semicolon resuming tag mode, I certainly agree that code looks horrible when too much is crammed into one line, but so does this:
```
nav
    div
        ul
            li
                a href="/foo"
                    h2 - Foo
            li
                a href="/bar"
                    h2 - Bar                        
```
compared to
```
nav; div; ul
    li; a href="/foo"; h2 - Foo
    li; a href="/bar"; h2 - Bar
```
The point of most of these changes is to give developers more style options - like whitespace in unparenthesized expressions - and trust them not to abuse it. As for documentation, I personally feel it's pretty self-explanatory.

The only other issue I can think of is whether tags after a semicolon become children or siblings of the previous tag - in this example they become children, which I think is more useful, though I suppose that doesn't quite match javascript's behavior...

P.S.: I love the `--` multi-line blocks!

**Comment by mlrawlings** [comment]
Just FYI, to support what @Hesulan is pushing for only requires replacing [Parser.js#L2042-L2063](https://github.com/mlrawlings/htmljs-parser/blob/1d231f1d22e1ca942e55107098569d92c0fbb519/Parser.js#L2042-L2063) with:
```js
parser.rewind(2);
```

**Pull request merged**
